### ISSUE TITLE
Legacy of Kain: Defiance can't map buttons to LT/RT triggers on Xbox One pad.

### ISSUE THREAD

**Issue by r2rX** [samuelgr/Xidi#7]
Hey there,

On the back of the successful fix for Soul Reaver 2 (https://github.com/samuelgr/Xidi/issues/6), I decided to test out Xidi 1.0.2 with Legacy of Kain: Defiance. The game loads up just fine and the options menu detects a gamepad.....but it's not possible to assign any commands to the throttle buttons; LT and RT.

This behavior is similar when running Defiance (and Soul Reaver 2) with vanilla DirectInput on an XInput gamepad (as the throttle triggers are registered as an axis, as opposed to digital buttons).

As part of the appeal of using Xidi is that it can enforce the throttle triggers to work as digital buttons, it's surprising that Xidi works fine with Soul Reaver 2 and not with Defiance.

Please let me know if there's any further info I can provide and i'm ready & able to test.

**Comment by samuelgr** [comment]
Does it work with Start, Back, LS, and RS?

**Comment by r2rX** [comment]
Start, Back, Left Stick and Right Stick are registered and work in the game.

It seems that the game is detecting LT and RT on a shared axis. Within the options menu, there are several axis presets that can be selected for the secondary stick. They are as follows:

(Legend: direction of right analog stick=camera direction)

```
**Z-RX:**
left=up
right=down
up=none
down=none
LT=right
RT=left


**RX-Z:**
left=left
right=right
up=none
down=none
LT=down
RT=up


**Z-RY:**
left=none
right=none
up=up
down=down
LT=right
RT=left


**RY-Z:**
left=none
right=none
up=left
down=right
LT=down
RT=up


**RX-RY:**
left=left
right=right
up=up
down=down
LT=none
RT=none


**RY-RX:**
left=up
right=down
up=left
down=right
LT=down
RT=up
```

The ideal preset is RX-RY. Despite the camera controls mapping properly on the right analog stick, LT and RT are not available to map any controls to.

**Comment by samuelgr** [comment]
It sounds like Xidi is not being loaded at all. Which version (dinput, dinput8, or winmm) of Xidi are you using? Are you sure it is the right version for this game?

**Comment by r2rX** [comment]
Hey @samuelgr . I tested the x86 version of dinput, dinput8 and winmm. The results, however, are the same irrespective.

**Comment by samuelgr** [comment]
This covers all three forms of Xidi; thanks for doing that test.

I did some digging, and it looks like this game (as well as a random selection of other games) loads DirectInput in a way that cannot be intercepted just by dropping in a replacement DLL file.  In other words, getting Xidi loaded into this game will require some fairly invasive techniques.

The good news is I have a solution in mind and am reasonably confident it will work.  The bad news is, while I do not anticipate it will take a terribly long time, at the moment I cannot provide an ETA on said solution.

**Comment by r2rX** [comment]
> 
> 
> This covers all three forms of Xidi; thanks for doing that test.
> 
> I did some digging, and it looks like this game (as well as a random selection of other games) loads DirectInput in a way that cannot be intercepted just by dropping in a replacement DLL file. In other words, getting Xidi loaded into this game will require some fairly invasive techniques.
> 
> The good news is I have a solution in mind and am reasonably confident it will work. The bad news is, while I do not anticipate it will take a terribly long time, at the moment I cannot provide an ETA on said solution.

Hey @samuelgr . Glad to have helped with the testing.

It's great that you have a solution in mind and we'll wait patiently till you release a build for us to test. Thanks again. :)

**Comment by r2rX** [comment]
Hi @samuelgr . Hope you've been keeping well during this, shall we say, interesting year. Just wanted to send regards and we're awaiting progress with bated breath. :)

**Comment by samuelgr** [comment]
Hi @r2rX, thanks for the well-wishes, and to you as well. I should hopefully have something to share in the not-too-distant future.

**Comment by r2rX** [comment]
> 
> 
> Hi @r2rX, thanks for the well-wishes, and to you as well. I should hopefully have something to share in the not-too-distant future.

Awesome! Looking forward to it. ;)

**Comment by samuelgr** [comment]
Good news: the technical solution I had in mind for this is implemented and seems to be working.

**Comment by r2rX** [comment]
Great job @samuelgr ! Once it's available, I'll be sure to test it. ;)

**Comment by samuelgr** [comment]
I am still working on packaging this in a more user-friendly format, but for now here is a preview that can be used for testing. It is not a simple drop-in replacement for previous versions of Xidi - instructions on how to use this package follow.

[Xidi-v1.1.0-pre.1_defiance.zip](https://github.com/samuelgr/Xidi/files/5663362/Xidi-v1.1.0-pre.1_defiance.zip)

Contained within this package is a new form of Xidi, a "hook module" that is intended to be loaded by [Hookshot](https://github.com/samuelgr/Hookshot), another of my projects. To use this package:

1. Extract the contents of the archive above to the directory containing the game's executable, `defiance.exe`.
1. Download a [release of Hookshot](https://github.com/samuelgr/Hookshot/releases/) and place the files `Hookshot.32.exe` and `Hookshot.32.dll` into the same directory as the game's executable.
1. Launch the game by doing a drag-and-drop operation in File Explorer. Drag `defiance.exe` and drop it on top of `Hookshot.32.exe`.

The reason why this is all needed is that this game does not load DirectInput via the standard DLL mechanism the way other games do. Rather, it uses [COM](https://docs.microsoft.com/en-us/windows/win32/com/component-object-model--com--portal), which causes Windows to bypass Xidi entirely. Launching the game in this way allows this process to be intercepted such that DirectInput requests can be redirected back to Xidi.

@r2rX please give this a go and let me know how things work or if you need any help. Thanks for offering to help me test.

**Comment by r2rX** [comment]
I am glad to report that it is working beautifully, @samuelgr .

All buttons, including the triggers, are registered properly and it works great now! Additionally, going in to the game's controller options, setting the gamepad type to analogue and the secondary stick to Z-RZ has both analog sticks working perfectly.

Force feedback is the only thing that isn't working (as it's greyed out in the controller options menu). Not sure if this is easy to get working or if you'd be interested in looking at it but that's the only niggle I can report back. :D

>
>
> @r2rX please give this a go and let me know how things work or if you need any help. Thanks for offering to help me test.

My sincerest pleasure, dude. If anyone is due thanks, it's to you. With this effort, you've ensured there's a means for fans (old and new) to have full XInput controller support for this game (actually, the whole LoK series!). And for any other titles that interact with DirectInput as Defiance does, they should also work (although not tested, obviously). So thank you very much!

The only other thing I can think of, aside from force feedback support, is whether it's possible to incorporate hookshot in a way that the shortcut/executable of the game can be run and automatically load through Hookshot.32.exe and respective .dll (to make the experience as simple as launching the shortcut or .exe directly, without having to drag & drop it in to Hookshot32.exe).

All-in-all, fantastic job dude! Please let me know if there's any other feedback or testing you'd like me to run.

**Comment by samuelgr** [comment]
> I am glad to report that it is working beautifully, @samuelgr .

Wonderful, very glad to hear it. I will mark this issue as closed, with the fix being the hook module.

> Note: The D-pad buttons aren't recognized but I honestly don't recall if they originally did and I don't have a DInput pad to confirm this.

I was wondering about that myself, but I tried the game without Xidi and did not see the d-pad working there either. There is nothing special about the way the d-pad is presented in either case, so it is possible the game just ignores all POVs.

> EDIT: I had mentioned the prospect of making it more user-friendly (preferably launching the games shortcut or .exe directly without dragging and dropping) but I forgot you mentioned that in the previous post so I know you're on the case. ;)

Yes, and I completely agree with the suggestion. I think this is something better fixed in Hookshot than in Xidi, and in any case I plan to get that done before packaging up a release.

In the meantime, if you want to keep using the pre-release package to play the game, you can create a shortcut to `Hookshot.32.exe`, right-click the shortcut and get to its properties, then in the "Target" field add the full path to `defiance.exe` right after the path to `Hookshot.32.exe`. So for example the "Target" field might look like this (make sure to include the quote characters): `"D:\Legacy of Kain Defiance\Hookshot.32.exe" "D:\Legacy of Kain Defiance\defiance.exe"`.

> Force feedback is the only thing that isn't working

Force feedback is currently not implemented in Xidi, but it is on my radar as a possible new feature for a future version.

> If anyone is due thanks, it's to you.

Appreciated. I am glad to see that people other than myself are using Xidi and am happy to make it work with as many games as I reasonably can.

**Comment by r2rX** [comment]
> 
> 
> In the meantime, if you want to keep using the pre-release package to play the game, you can create a shortcut to `Hookshot.32.exe`, right-click the shortcut and get to its properties, then in the "Target" field add the full path to `defiance.exe` right after the path to `Hookshot.32.exe`. So for example the "Target" field might look like this (make sure to include the quote characters): `"D:\Legacy of Kain Defiance\Hookshot.32.exe" "D:\Legacy of Kain Defiance\defiance.exe"`.

Thanks for the tip. The shortcut works fine. 👍 

>
> 
> Force feedback is currently not implemented in Xidi, but it is on my radar as a possible new feature for a future version.

Fantastic! Once implemented, it should satisfy the main features necessary for a complete experience, at least from the users perspective.

> 
> 
> Appreciated. I am glad to see that people other than myself are using Xidi and am happy to make it work with as many games as I reasonably can.

Here here!

**Comment by samuelgr** [comment]
The fix for this is part of v2.0.0. Hookshot also got some updates, so the process should be more user-friendly once the HookModule is set up.

**Comment by r2rX** [comment]
> 
> 
> The fix for this is part of v2.0.0. Hookshot also got some updates, so the process should be more user-friendly once the HookModule is set up.

Hey @samuelgr , great job! Xidi v2.0.0, with Hookshot, works as advertised. :) Once Force Feedback is implemented, it will help cement future proofing for full support of DInput titles!

Keep up the awesome work, dude. ;)

**Comment by microsample** [comment]
Triggers still not working for me, installed all available releases.
Tried pre-release, but Hookshot.32.exe gives error 
`the procedure entry point IsWow64Process2 could not be located in the dynamic link library KERNEL32.DLL`
I'm using Windows 7, maybe there is a problem?

**Comment by samuelgr** [comment]
Both Xidi and Hookshot are built for Windows 10, with no promises whatsoever that they will work on older versions of Windows. IsWow64Process2 is an API [introduced in Windows 10 v1511](https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process2#requirements), hence the error.

**Comment by UncleStark** [comment]
Hello, guys. I use xidi 4.0.0 and Hookshot-v1.2.0. Triggers work in game, but vibration option still grayed. is there a fix for this?

**Comment by samuelgr** [comment]
@UncleStark could you please file a separate issue for this?

**Comment by samuelgr** [comment]
Actually I just did it myself. We can track vibration for this game in #23.

**Comment by BParks21** [comment]
How would I do this and launch the game from steam and it hook the .exe?

**Comment by r2rX** [comment]
@BParks21 

1. Make sure the latest [Visual C++ Runtime for Visual Studio 2022](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist) is installed (both X86 and X64 if on 64bit OS).
2. Open the game folder and rename defiance.exe to _HookshotLauncher_defiance.exe
3. Extract Hookshot.32.dll, Hookshot.32.exe and HookshotLauncher.32.exe from the Hookshot package into the game folder and rename HookshotLauncher.32.exe to defiance.exe .
4. Extract Xidi.HookModule.32.dll and dinput8.dll, from the Win32 folder in Xidi package, into the game folder.

You don't need to add anything in the properties for the game on Steam so ensure the properties field is cleared before launching.

**Comment by BParks21** [comment]
Doesn't seem to work, the setup for the game launches and says failed to initialize with current settings. I change them and it just keeps relaunching it. Maybe it doesn't work with my d3d8 to 9 wrapper. I got it working with the old method you posted but there was no way for me to launch it from steam. I'm using the known widescreen hack and the dxwrapper to get the game running properly. I have a dinput wireless adapter from mayflash that allows me to use practically any controller in dinput mode. I wanted to not have to switch to it and just use my series x controller. Oh well I'll just keep using my dinput wireless adapter.
